### ISSUE TITLE
refactor: toplantı sonrası istenilen değişiklik listesi

### ISSUE THREAD

**Issue by hkulekci** [acikkaynak/deprem-yardim-com#44]
- [x] Hatay "Yardım Adresi Bİldirim Formu"nda seçili olarak gelmesi gerekiyor.  #45
 - [x] IP adresi Address Notofication Formunda cloudflare IP olarak geliyor. Bunun real IP olması gerekiyor. #46
 - [x] API endpointinden dönen değerler afetharita'nın beklediği hale getirildi #47
